<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Today's Collections - {{ now()->format('d M, Y') }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            margin: 20px;
        }

        /* Header Styles */
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 15px;
        }

        .company-info {
            text-align: right;
        }

        .company-info h2 {
            margin: 0;
            color: #2c3e50;
        }

        /* Report Metadata */
        .report-meta {
            margin-bottom: 20px;
            padding: 15px;
            background: #f5f5f5;
            border-radius: 4px;
        }

        /* Table Styling */
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        th {
            background-color: #2c3e50;
            color: white;
            padding: 10px;
            text-align: left;
        }

        td {
            padding: 8px;
            border: 1px solid #ddd;
        }

        tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        /* Signature Column */
        .signature-column {
            width: 150px;
            height: 40px;
            background: #f8f9fa;
        }

        /* Summary Section */
        .summary {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 15px;
            margin: 15px 0;
            padding: 15px;
            background: #f5f5f5;
            border-radius: 4px;
        }

        .summary-item {
            text-align: center;
        }

        /* Footer */
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #ccc;
            text-align: center;
            color: #666;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="company-info">
            <h2>{{ $company->name ?? config('app.name') }}</h2>
            <p>{{ $company->address ?? '123 Main Street, Kaluwanchikudy' }}</p>
            <p>Tel: {{ $company->phone ?? '+94 112 345 678' }}</p>
            @if($company->email ?? false)<p>Email: {{ $company->email }}</p>@endif
        </div>
    </div>

    <div class="report-meta">
        <h3>Today's Collections Report</h3>
        <div class="filters">
            <p><strong>Date:</strong> {{ now()->format('d M, Y') }}</p>
            @if($filters['centerId'])
            <p><strong>Center:</strong> {{ \App\Models\Center::find($filters['centerId'])->name }}</p>
            @endif
            <p><strong>Generated At:</strong> {{ now()->format('Y-m-d H:i') }}</p>
        </div>
    </div>

    <div class="summary">
        <div class="summary-item">
            <h4>{{ $collectionCount }}</h4>
            <p>Total Collections</p>
        </div>
        <div class="summary-item">
            <h4>{{ number_format($totalPending, 2) }}</h4>
            <p>Pending Amount</p>
        </div>
        <div class="summary-item">
            <h4>{{ Auth::user()->name }}</h4>
            <p>Generated By</p>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>#</th>
                <th>Customer</th>
                <th>Center</th>
                <th>Due Amount</th>
                <th>Paid Amount</th>
                <th>Pending</th>
                <th>Signature</th>
            </tr>
        </thead>
        <tbody>
            @foreach($collections as $index => $collection)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>
                    <strong>{{ $collection->loan->customer->full_name }}</strong><br>
                    {{ $collection->loan->customer->phone }}
                </td>
                <td>{{ $collection->loan->center->name }}</td>
                <td>{{ number_format($collection->due, 2) }}</td>
                <td>{{ number_format($collection->paid, 2) }}</td>
                <td>{{ number_format($collection->pending_due, 2) }}</td>
                <td class="signature-column">
                    <div style="border-bottom: 1px solid #000; width: 80%; margin: 15px auto 5px; position: relative;">
                        <span style="position: absolute; bottom: -18px; left: 50%; transform: translateX(-50%);
                                   font-size: 8px; color: #666;">
                            (Customer Signature)
                        </span>
                    </div>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ config('app.name') }} | {{ config('app.url') }}<br>
        Page <span class="pageNumber"></span> of <span class="totalPages"></span>
    </div>
</body>
</html>
